/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.ruby.ui.contentassist;

import org.xtext.example.ruby.ui.contentassist.AbstractRubyProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RubyProposalProvider extends AbstractRubyProposalProvider {
}
