/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.ruby.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.ruby.ui.internal.RubyActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RubyExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RubyActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RubyActivator.getInstance().getInjector(RubyActivator.ORG_XTEXT_EXAMPLE_RUBY_RUBY);
	}
	
}
