/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.ruby.validation;

import org.xtext.example.ruby.validation.AbstractRubyValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class RubyValidator extends AbstractRubyValidator {
}
