/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.ruby;

import org.xtext.example.ruby.AbstractRubyRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RubyRuntimeModule extends AbstractRubyRuntimeModule {
}
