/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.ruby.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.ruby.ui.AbstractRubyUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class RubyUiModule extends AbstractRubyUiModule {
  public RubyUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
