/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.ruby.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.ruby.ide.contentassist.antlr.internal.InternalRubyParser;
import org.xtext.example.ruby.services.RubyGrammarAccess;

public class RubyParser extends AbstractContentAssistParser {

	@Inject
	private RubyGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalRubyParser createParser() {
		InternalRubyParser result = new InternalRubyParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getBeginAccess().getAlternatives_2(), "rule__Begin__Alternatives_2");
					put(grammarAccess.getRescueAccess().getAlternatives_2(), "rule__Rescue__Alternatives_2");
					put(grammarAccess.getEnsureAccess().getAlternatives_2(), "rule__Ensure__Alternatives_2");
					put(grammarAccess.getBeginAccess().getGroup(), "rule__Begin__Group__0");
					put(grammarAccess.getRescueAccess().getGroup(), "rule__Rescue__Group__0");
					put(grammarAccess.getEnsureAccess().getGroup(), "rule__Ensure__Group__0");
					put(grammarAccess.getModelAccess().getBeginAssignment(), "rule__Model__BeginAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public RubyGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RubyGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
