/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.ruby


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RubyStandaloneSetup extends RubyStandaloneSetupGenerated {

	def static void doSetup() {
		new RubyStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
