/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.ruby


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class RubyRuntimeModule extends AbstractRubyRuntimeModule {
}
