/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.ruby.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.ruby.parser.antlr.internal.InternalRubyParser;
import org.xtext.example.ruby.services.RubyGrammarAccess;

public class RubyParser extends AbstractAntlrParser {

	@Inject
	private RubyGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRubyParser createParser(XtextTokenStream stream) {
		return new InternalRubyParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public RubyGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RubyGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
