/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.ruby.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.ruby.RubyRuntimeModule;
import org.xtext.example.ruby.RubyStandaloneSetup;
import org.xtext.example.ruby.ide.RubyIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class RubyIdeSetup extends RubyStandaloneSetup {
  @Override
  public Injector createInjector() {
    RubyRuntimeModule _rubyRuntimeModule = new RubyRuntimeModule();
    RubyIdeModule _rubyIdeModule = new RubyIdeModule();
    return Guice.createInjector(Modules2.mixin(_rubyRuntimeModule, _rubyIdeModule));
  }
}
