/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.ruby.ide;

import org.xtext.example.ruby.ide.AbstractRubyIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RubyIdeModule extends AbstractRubyIdeModule {
}
