/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.ruby.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.ruby.ui.internal.RubyActivator;

public class RubyUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RubyActivator.getInstance().getInjector("org.xtext.example.ruby.Ruby");
	}

}
